/**
 * PRACTICE STATE MODEL (Architecture Reference)
 * 
 * Practice.jsx now separates concerns into distinct state fields:
 * 
 * ╔════════════════════════════════════════════════════════════════════════╗
 * ║                         INPUT STATE                                    ║
 * ╠════════════════════════════════════════════════════════════════════════╣
 * ║  inputValue: string                                                    ║
 * ║    - Raw user input from keyboard/buttons                             ║
 * ║    - Updated on keystroke                                            ║
 * ║    - Not used for any internal processing                            ║
 * ╚════════════════════════════════════════════════════════════════════════╝
 * 
 * ╔════════════════════════════════════════════════════════════════════════╗
 * ║                      RESOLVED WORDS & DISPLAY                         ║
 * ╠════════════════════════════════════════════════════════════════════════╣
 * ║  sourceText: string                                                    ║
 * ║    - The actual word/phrase being practiced (after trim)             ║
 * ║    - Used for: targetWord (recorder/coaching/archive)               ║
 * ║    - Used for: TTS input (synthesize)                               ║
 * ║    - NEVER contains helper text formatting                          ║
 * ║    - Example: "excelente" (not "excelente — 'eks-se-len-te'")      ║
 * ║                                                                      ║
 * ║  helperText: string                                                  ║
 * ║    - Language-specific learner pronunciation helper                 ║
 * ║    - Generated by getLearnerHelper(sourceText, language)            ║
 * ║    - Used ONLY for display above animation tokens                  ║
 * ║    - Example: "eks-se-len-te" (for Spanish "excelente")            ║
 * ║    - Passed to DualHeadAnimation as playLabel.helper                ║
 * ╚════════════════════════════════════════════════════════════════════════╝
 * 
 * ╔════════════════════════════════════════════════════════════════════════╗
 * ║                  ANIMATION & TTS DATA                                 ║
 * ╠════════════════════════════════════════════════════════════════════════╣
 * ║  pronunciation: string                                                ║
 * ║    - Animation phoneme display (internal use only)                   ║
 * ║    - From: phonemeResolver.resolve(sourceText, language).pronunciation ║
 * ║    - Passed to DualHeadAnimation as playLabel.phonetic              ║
 * ║                                                                      ║
 * ║  timeline: array                                                      ║
 * ║    - Phoneme timeline scaled to audio duration                      ║
 * ║    - [{phoneme, label, frame, startMs, endMs, ...}]               ║
 * ║    - From: phonemeResolver.resolve() + audio duration scaling      ║
 * ║    - Used by: DualHeadAnimation (sprite animation sync)            ║
 * ║                                                                      ║
 * ║  audioUrl: string | null                                              ║
 * ║    - Object URL to MP3 blob from openaiTTS                         ║
 * ║    - From: provider.synthesize(sourceText, language)               ║
 * ║    - Passed to: DualHeadAnimation (audio playback)                 ║
 * ║    - Speed: 50% (set in AudioPlayer init)                          ║
 * ╚════════════════════════════════════════════════════════════════════════╝
 * 
 * ╔════════════════════════════════════════════════════════════════════════╗
 * ║                  LOADING & PLAYBACK STATE                             ║
 * ╠════════════════════════════════════════════════════════════════════════╣
 * ║  isLoadingAudio: boolean                                              ║
 * ║    - True while openaiTTS is in progress                            ║
 * ║    - Used to disable play button / show loading spinner             ║
 * ║                                                                      ║
 * ║  playCount: number                                                    ║
 * ║    - Incremented when user clicks Play                             ║
 * ║    - Signals DualHeadAnimation to start playback                   ║
 * ║    - Separate from isPlaying (controls audio + animation sync)    ║
 * ║                                                                      ║
 * ║  coachingData: object | null                                          ║
 * ║    - Results from analyzeRecording backend function               ║
 * ║    - Contains: score, transcript, phonemeBreakdown, suggestions   ║
 * ║    - Passed to: CoachingBox (feedback display)                    ║
 * ╚════════════════════════════════════════════════════════════════════════╝
 * 
 * ╔════════════════════════════════════════════════════════════════════════╗
 * ║                  CURRICULUM & HISTORY                                 ║
 * ╠════════════════════════════════════════════════════════════════════════╣
 * ║  activeCurriculumLesson: object | null                                 ║
 * ║    - Current lesson context (if from Curriculum)                    ║
 * ║    - Contains: id, word, passScore                                 ║
 * ║                                                                      ║
 * ║  completedIds: Set                                                    ║
 * ║    - Lesson IDs that have been completed                           ║
 * ║    - Stored in localStorage                                        ║
 * ╚════════════════════════════════════════════════════════════════════════╝
 * 
 * KEY SEPARATION PRINCIPLES
 * ─────────────────────────────────────────────────────────────────────────
 * 
 * ✗ WRONG:  setResolvedWord("excelente — 'eks-se-len-te'")
 *           Then use resolvedWord for targetWord, TTS, recordings
 *           (Mixes display formatting with operational data)
 * 
 * ✓ RIGHT:  setSourceText("excelente")
 *           setHelperText("eks-se-len-te")
 *           Use sourceText for: targetWord, TTS, recordings
 *           Use helperText for: display only
 *           (Separates concerns cleanly)
 * 
 * ✗ WRONG:  Use animation token labels as learner helper text
 *           (e.g., showing "k g s e l e n t e" to learner)
 * 
 * ✓ RIGHT:  Use language-specific helper: "eks-se-len-te"
 *           Keep animation tokens internal (for lip-sync only)
 * 
 * ✗ WRONG:  Modify text before TTS ("excelente" → "eh-ksay...")
 * 
 * ✓ RIGHT:  Pass original text unchanged to TTS
 *           OpenAI TTS handles language naturally
 * 
 * DATA FLOW: INPUT → SOURCE → ANIMATION TOKENS, HELPER, TTS AUDIO
 * ─────────────────────────────────────────────────────────────────────────
 * 
 * User types "excelente"
 *   ↓ (inputValue)
 * resolvePhonemes() called with debounce (120ms)
 *   ├─ setSourceText("excelente")
 *   ├─ setHelperText(getLearnerHelper("excelente", "es")) → "eks-se-len-te"
 *   ├─ resolveTokens(sourceText, language) → animation tokens
 *   │  └─ setPronunciation(result.pronunciation)
 *   │  └─ setTimeline(result.phonemeTimeline)
 *   └─ return { ttsText: sourceText, result }
 *   ↓ (synthesizeAudio debounce 600ms)
 * provider.synthesize(sourceText, language)
 *   ↓
 * openaiTTS({text: "excelente", language: "es", voice: "onyx", ...})
 *   ↓
 * [Backend logs] sourceText="excelente" | ttsText="excelente" | lang=es | model=tts-1-hd
 *   ↓
 * audio_base64 → decodeToBlob → setAudioUrl(objectUrl)
 *   ↓
 * DualHeadAnimation receives:
 *   - playLabel.word = "excelente" (sourceText)
 *   - playLabel.helper = "eks-se-len-te" (helperText) — displayed above phonemes
 *   - playLabel.phonetic = "..." (animation tokens)
 *   - timeline = [...] (scaled to audio duration)
 *   - audioUrl = "blob:..." (MP3 at 50% speed)
 *
 * DEPRECATED FIELDS (Removed)
 * ─────────────────────────────────────────────────────────────────────────
 * resolvedWord (DELETED)
 *   - Was mixing helper text with source text
 *   - Replaced by: sourceText, helperText, pronunciation
 */

export default function PracticeStateModel() {
  return null; // Documentation only
}