const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },

  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },

  stop_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.46,
    nasal: 0,
    velocity: 0.48,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },

  fricative_weak: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.56,
    nasal: 0,
    velocity: 0.46,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },

  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.8,
    nasal: 0,
    velocity: 0.64,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },

  affricate: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.72,
    nasal: 0,
    velocity: 0.66,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },

  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0,
    nasal: 0.72,
    velocity: 0.4,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },

  nasal_vowel: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.28,
    nasal: 0.46,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },

  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.4,
    nasal: 0,
    velocity: 0.32,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },

  uvular_fricative: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.82,
    nasal: 0,
    velocity: 0.68,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },

  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.32,
    nasal: 0,
    velocity: 0.26,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },

  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.62,
    nasal: 0,
    velocity: 0.4,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },

  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.66,
    nasal: 0,
    velocity: 0.42,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;