/**
 * SoundMirror pronunciation helper — English (US)
 *
 * English helper text is generated by pack-owned grapheme/phoneme rules. The
 * 500+ practice list is content, not a runtime pronunciation dictionary.
 * A deliberately small reviewed set protects the visible presets and control
 * examples; all other input is generated on demand by the same rule engine.
 */

import universal500 from './universal500';
import { phonemeLookup } from './phonemeSystem';
import { renderEnglishHelperWord } from './helperRenderer';
import {
  ENGLISH_PRESET_WORDS as ENGLISH_RUNTIME_WORDS,
  ENGLISH_PRESET_PHRASES as ENGLISH_RUNTIME_PHRASES,
} from './presets';

export const ENGLISH_PRESET_WORDS = Object.freeze(
  ENGLISH_RUNTIME_WORDS.map((item) => item.practice)
);

export const ENGLISH_PRESET_PHRASES = Object.freeze(
  ENGLISH_RUNTIME_PHRASES.map((item) => item.practice)
);

/**
 * Reviewed controls, not a word dictionary. This mirrors the small reviewed
 * example set used by the other completed language packs.
 */
export const REVIEWED_ENGLISH_HELPERS = Object.freeze({
  hello: 'h-eh-l-oh',
  hi: 'h-ai',
  smile: 's-m-ai-l',
  thanks: 'th-a-ng-k-s',
  sorry: 's-o-r-ee',
  yes: 'y-eh-s',
  no: 'n-oh',
  welcome: 'w-eh-l-k-uh-m',
  goodbye: 'g-uh-d-b-ai',
  kiss: 'k-i-s',
  good: 'g-uh-d',
  morning: 'm-or-n-ee-ng',
  excuse: 'ehk-sk-yooz',
  me: 'm-ee',
  evening: 'ee-v-en-ee-ng',
  how: 'h-ow',
  are: 'ar',
  you: 'y-oo',
  i: 'ai',
  am: 'a-m',
  fine: 'f-ai-n',
  thank: 'th-a-ng-k',
  see: 's-ee',
  soon: 's-oo-n',
  night: 'n-ai-t',
  cream: 'k-r-ee-m',
});

const PHONEME_SOURCE = 'pack-rule-engine';

const HELPER_CHUNK_TO_PHONEMES = Object.freeze({
  a: Object.freeze(['a']),
  ah: Object.freeze(['aa']),
  uh: Object.freeze(['ah']),
  eh: Object.freeze(['e']),
  e: Object.freeze(['e']),
  ee: Object.freeze(['ee']),
  i: Object.freeze(['i']),
  ih: Object.freeze(['i']),
  u: Object.freeze(['ue']),
  oo: Object.freeze(['oo']),
  o: Object.freeze(['o']),
  oh: Object.freeze(['ow']),
  ow: Object.freeze(['aw']),
  aw: Object.freeze(['o']),
  ai: Object.freeze(['ai']),
  ahy: Object.freeze(['ai']),
  ei: Object.freeze(['ei']),
  oi: Object.freeze(['oi']),
  oy: Object.freeze(['oi']),
  er: Object.freeze(['er']),
  ur: Object.freeze(['er']),
  ar: Object.freeze(['aa', 'r']),
  air: Object.freeze(['e', 'r']),
  eer: Object.freeze(['ee', 'r']),
  ihr: Object.freeze(['i', 'r']),
  or: Object.freeze(['o', 'r']),

  b: Object.freeze(['b']),
  p: Object.freeze(['p']),
  t: Object.freeze(['t']),
  d: Object.freeze(['d']),
  k: Object.freeze(['k']),
  c: Object.freeze(['k']),
  g: Object.freeze(['g']),
  m: Object.freeze(['m']),
  n: Object.freeze(['n']),
  ng: Object.freeze(['ng']),
  f: Object.freeze(['f']),
  v: Object.freeze(['v']),
  s: Object.freeze(['s']),
  z: Object.freeze(['z']),
  sh: Object.freeze(['sh']),
  zh: Object.freeze(['zh']),
  th: Object.freeze(['th']),
  dh: Object.freeze(['dh']),
  h: Object.freeze(['h']),
  ch: Object.freeze(['ch']),
  j: Object.freeze(['j']),
  r: Object.freeze(['r']),
  l: Object.freeze(['l']),
  y: Object.freeze(['y']),
  w: Object.freeze(['w']),
  ks: Object.freeze(['k', 's']),

  an: Object.freeze(['a', 'n']),
  en: Object.freeze(['ah', 'n']),
  in: Object.freeze(['i', 'n']),
  bee: Object.freeze(['b', 'ee']),
  heh: Object.freeze(['h', 'e']),
  lo: Object.freeze(['l', 'ow']),
  ohf: Object.freeze(['o', 'f']),
  fen: Object.freeze(['f', 'ah', 'n']),
  ful: Object.freeze(['f', 'ah', 'l']),
  sug: Object.freeze(['s', 'ah', 'g']),
  ter: Object.freeze(['t', 'er']),
  ti: Object.freeze(['t', 'i']),
  tuh: Object.freeze(['t', 'ah']),
  yer: Object.freeze(['y', 'er']),
  yoo: Object.freeze(['y', 'oo']),
});

const SEGMENTABLE_HELPER_CHUNKS = Object.freeze(
  Object.keys(HELPER_CHUNK_TO_PHONEMES).sort((left, right) => right.length - left.length)
);

const HELPER_CHUNK_DISPLAY = Object.freeze({
  // English FOOT /ʊ/ and STRUT /ʌ/ may both be shown to a learner as "uh",
  // but their pack-owned phoneme identities remain distinct in each group.
  u: 'uh',
  ihr: 'eer',
});

/**
 * Learner-facing spell-outs may be more explicit than the canonical phoneme
 * sequence. For example, "view" is graded as /v j u:/, while the visible cue
 * deliberately walks the learner through the glide as "v-ee-oo-w".
 */
const LEARNER_DISPLAY_OVERRIDES = Object.freeze({
  view: 'v-ee-oo-w',
});

// Isolated English homographs cannot be disambiguated without sentence
// meaning. The pack keeps a sensible practice default and certifies the other
// common pronunciation as an explicit alternate instead of pretending either
// reading is universally correct.
const HOMOGRAPH_ALTERNATE_HELPERS = Object.freeze({
  live: Object.freeze(['l-ai-v']),
  use: Object.freeze(['y-oo-s']),
});

function normalizeWord(value = '') {
  return String(value || '')
    .toLowerCase()
    .replace(/[^a-z']/g, '');
}

function wordsFromText(value = '') {
  return String(value || '')
    .trim()
    .split(/\s+/)
    .map(normalizeWord)
    .filter(Boolean);
}

function normalizeText(value = '') {
  return wordsFromText(value).join(' ');
}

function segmentHelperChunk(chunk = '') {
  const normalized = String(chunk || '').trim().toLowerCase();
  if (!normalized) return [];

  if (Object.prototype.hasOwnProperty.call(HELPER_CHUNK_TO_PHONEMES, normalized)) {
    return [...HELPER_CHUNK_TO_PHONEMES[normalized]];
  }

  const memo = new Map();

  function walk(index) {
    if (index === normalized.length) return [];
    if (memo.has(index)) return memo.get(index);

    for (const candidate of SEGMENTABLE_HELPER_CHUNKS) {
      if (!normalized.startsWith(candidate, index)) continue;
      const rest = walk(index + candidate.length);
      if (rest !== null) {
        const result = [
          ...HELPER_CHUNK_TO_PHONEMES[candidate],
          ...rest,
        ];
        memo.set(index, result);
        return result;
      }
    }

    memo.set(index, null);
    return null;
  }

  return walk(0);
}

function helperToGroups(helper = '') {
  const chunks = String(helper || '')
    .trim()
    .toLowerCase()
    .split('-')
    .map((chunk) => chunk.trim())
    .filter(Boolean);

  const groups = [];

  for (const chunk of chunks) {
    const phonemes = segmentHelperChunk(chunk);
    if (!Array.isArray(phonemes) || phonemes.length === 0) return [];
    if (phonemes.some((phoneme) => !phonemeLookup[phoneme])) return [];

    groups.push({
      helper: HELPER_CHUNK_DISPLAY[chunk] || chunk,
      ruleChunk: chunk,
      phonemes,
      helperAuthority: true,
      phonemeSource: PHONEME_SOURCE,
    });
  }

  return groups;
}

function unresolvedWordResult(sourceText, normalizedText, issues) {
  return {
    version: 9,
    language: 'en-US',
    kind: 'word',
    sourceText,
    normalizedText,
    status: 'unresolved',
    approved: false,
    reviewRequired: true,
    unresolved: true,
    humanReviewed: false,
    mechanicallyValidated: false,
    helperAuthority: false,
    phonemeSource: null,
    display: '',
    helperText: '',
    pronunciation: '',
    phonemes: [],
    groups: [],
    alternates: [],
    approvalSource: null,
    creationMethod: null,
    validation: {
      valid: false,
      issues: Array.isArray(issues) ? issues : [String(issues || 'unresolved')],
    },
  };
}

export function buildEnglishPronunciationHelperWord(word = '') {
  const sourceText = String(word || '').trim();
  const normalizedText = normalizeWord(sourceText);
  if (!normalizedText) return unresolvedWordResult(sourceText, '', ['empty-word']);

  const reviewedHelper = REVIEWED_ENGLISH_HELPERS[normalizedText] || '';
  const ruleHelper = renderEnglishHelperWord(normalizedText);
  const groups = helperToGroups(ruleHelper);
  const phonemes = groups.flatMap((group) => group.phonemes);
  const generatedHelper = groups.map((group) => group.helper).join('-');
  const helper =
    LEARNER_DISPLAY_OVERRIDES[normalizedText] || reviewedHelper || generatedHelper;
  const valid = Boolean(ruleHelper) && Boolean(helper) && groups.length > 0 && phonemes.length > 0;

  if (!valid) {
    return unresolvedWordResult(sourceText, normalizedText, ['rule-generation-failed']);
  }

  const humanReviewed = Boolean(reviewedHelper);
  const alternates = (HOMOGRAPH_ALTERNATE_HELPERS[normalizedText] || []).map(
    (alternateHelper) => {
      const alternateGroups = helperToGroups(alternateHelper);
      return {
        helperText: alternateHelper,
        phonemes: alternateGroups.flatMap((group) => group.phonemes),
      };
    }
  );

  return {
    version: 9,
    language: 'en-US',
    kind: 'word',
    sourceText,
    normalizedText,
    status: 'approved',
    approved: true,
    reviewRequired: false,
    unresolved: false,
    humanReviewed,
    mechanicallyValidated: !humanReviewed,
    helperAuthority: true,
    phonemeSource: PHONEME_SOURCE,
    display: helper,
    helperText: helper,
    pronunciation: helper,
    phonemes,
    groups,
    alternates,
    approvalSource: humanReviewed ? 'reviewed-pack-example' : 'pack-rule-engine',
    creationMethod: humanReviewed ? 'reviewed-pack-example' : 'pack-rule-engine',
    validation: {
      valid: true,
      issues: [],
      representedPhonemes: [...phonemes],
    },
  };
}

export function buildEnglishPronunciationHelper(text = '') {
  const sourceText = String(text || '').trim();
  const normalizedWords = wordsFromText(sourceText);

  if (normalizedWords.length === 0) {
    return {
      version: 9,
      language: 'en-US',
      kind: 'text',
      sourceText,
      normalizedText: '',
      status: 'unresolved',
      approved: false,
      reviewRequired: true,
      unresolved: true,
      humanReviewed: false,
      mechanicallyValidated: false,
      helperAuthority: false,
      phonemeSource: null,
      words: [],
      phonemes: [],
      groups: [],
      display: '',
      helperText: '',
      pronunciation: '',
      approvalSource: null,
      creationMethod: null,
      validation: { valid: false, issues: ['empty-text'] },
    };
  }

  const words = normalizedWords.map(buildEnglishPronunciationHelperWord);
  const unresolvedWords = words.filter((word) => word.approved !== true);
  const valid = unresolvedWords.length === 0;
  const display = valid ? words.map((word) => word.display).join(' ') : '';
  const phonemes = valid ? words.flatMap((word) => word.phonemes) : [];
  const groups = valid
    ? words.flatMap((word, wordIndex) =>
        word.groups.map((group, groupIndex) => ({
          ...group,
          wordIndex,
          groupIndex,
          sourceWord: word.normalizedText,
        }))
      )
    : [];
  const humanReviewed = valid && words.every((word) => word.humanReviewed === true);
  const mechanicallyValidated =
    valid && words.every((word) => word.mechanicallyValidated === true);

  return {
    version: 9,
    language: 'en-US',
    kind: words.length === 1 ? 'word' : 'phrase',
    sourceText,
    normalizedText: normalizeText(sourceText),
    status: valid ? 'approved' : 'unresolved',
    approved: valid,
    reviewRequired: !valid,
    unresolved: !valid,
    humanReviewed,
    mechanicallyValidated,
    helperAuthority: valid,
    phonemeSource: valid ? PHONEME_SOURCE : null,
    words,
    phonemes,
    groups,
    alternates: words.length === 1 ? words[0].alternates : [],
    display,
    helperText: display,
    pronunciation: display,
    approvalSource: humanReviewed
      ? 'reviewed-pack-example'
      : mechanicallyValidated
        ? 'pack-rule-engine'
        : valid
          ? 'reviewed-and-rule-engine'
          : null,
    creationMethod: humanReviewed
      ? 'reviewed-pack-example'
      : mechanicallyValidated
        ? 'pack-rule-engine'
        : valid
          ? 'reviewed-and-rule-engine'
          : null,
    validation: {
      valid,
      issues: unresolvedWords.flatMap((word) =>
        (word.validation?.issues || []).map(
          (issue) => `${word.normalizedText || 'unknown'}:${issue}`
        )
      ),
    },
  };
}

function collectUniversal500Words() {
  return Array.isArray(universal500)
    ? universal500.flatMap((group) => (Array.isArray(group?.words) ? group.words : []))
    : [];
}

export function runEnglishPronunciationHelperAudit({
  presetWords = ENGLISH_PRESET_WORDS,
  presetPhrases = ENGLISH_PRESET_PHRASES,
  includeUniversal500 = true,
} = {}) {
  const entries = [
    ...presetWords.map((text) => ({ corpus: 'preset-word', text })),
    ...presetPhrases.map((text) => ({ corpus: 'preset-phrase', text })),
    ...(includeUniversal500 ? collectUniversal500Words() : []).map((text) => ({
      corpus: 'universal500',
      text,
    })),
  ];

  const seen = new Set();
  const items = [];

  for (const entry of entries) {
    const key = normalizeText(entry.text);
    if (!key || seen.has(key)) continue;
    seen.add(key);

    const result = buildEnglishPronunciationHelper(entry.text);
    items.push({
      corpus: entry.corpus,
      text: entry.text,
      status: result.status,
      approved: result.approved,
      reviewRequired: result.reviewRequired,
      unresolved: result.unresolved,
      humanReviewed: result.humanReviewed,
      mechanicallyValidated: result.mechanicallyValidated,
      helperAuthority: result.helperAuthority,
      phonemeSource: result.phonemeSource,
      display: result.display,
      phonemes: result.phonemes,
      validation: result.validation,
      creationMethods: result.words.map((word) => word.creationMethod),
      result,
    });
  }

  const approvedItems = items.filter((item) => item.status === 'approved');
  const reviewItems = items.filter(
    (item) => item.reviewRequired === true && item.unresolved !== true
  );
  const unresolvedItems = items.filter((item) => item.status === 'unresolved');
  const humanReviewedItems = items.filter((item) => item.humanReviewed === true);
  const mechanicallyValidatedItems = items.filter(
    (item) => item.mechanicallyValidated === true
  );

  return {
    version: 9,
    language: 'en-US',
    implemented: true,
    languageImplemented: true,
    summary: {
      total: items.length,
      approved: approvedItems.length,
      review: reviewItems.length,
      unresolved: unresolvedItems.length,
      humanReviewed: humanReviewedItems.length,
      mechanicallyValidated: mechanicallyValidatedItems.length,
      presetWords: items.filter((item) => item.corpus === 'preset-word').length,
      presetPhrases: items.filter((item) => item.corpus === 'preset-phrase').length,
      universal500: items.filter((item) => item.corpus === 'universal500').length,
    },
    items,
    approvedItems,
    reviewItems,
    unresolvedItems,
    humanReviewedItems,
    mechanicallyValidatedItems,
  };
}

export default {
  buildEnglishPronunciationHelper,
  buildEnglishPronunciationHelperWord,
  runEnglishPronunciationHelperAudit,
};
