const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.02,
    nasal: 0,
    velocity: 0.06,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  stop_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.4,
    nasal: 0,
    velocity: 0.42,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },
  fricative_weak: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.54,
    nasal: 0,
    velocity: 0.44,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.72,
    nasal: 0,
    velocity: 0.58,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  uvular_fricative: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.7,
    nasal: 0,
    velocity: 0.56,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.05,
    nasal: 0.7,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  nasal_vowel: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.24,
    nasal: 0.46,
    velocity: 0.34,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.38,
    nasal: 0,
    velocity: 0.3,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.3,
    nasal: 0,
    velocity: 0.24,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.58,
    nasal: 0,
    velocity: 0.36,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.62,
    nasal: 0,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  liaison_bridge: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.34,
    nasal: 0,
    velocity: 0.28,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;