const airflowOverrides = {
  p: { airflowClass: 'stop_unaspirated', oral: 0.38, velocity: 0.4, width: 'narrow', turbulent: false },
  b: { airflowClass: 'stop_unaspirated', oral: 0.36, velocity: 0.38, width: 'narrow', turbulent: false },
  t: { airflowClass: 'stop_unaspirated', oral: 0.4, velocity: 0.42, width: 'narrow', turbulent: false },
  d: { airflowClass: 'stop_unaspirated', oral: 0.38, velocity: 0.4, width: 'narrow', turbulent: false },
  k: { airflowClass: 'stop_unaspirated', oral: 0.44, velocity: 0.46, width: 'medium', turbulent: false },
  g: { airflowClass: 'stop_unaspirated', oral: 0.42, velocity: 0.44, width: 'medium', turbulent: false },
  f: { airflowClass: 'fricative_weak', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  v: { airflowClass: 'fricative_weak', oral: 0.56, velocity: 0.44, width: 'medium', turbulent: true },
  s: { airflowClass: 'fricative_strong', oral: 0.76, velocity: 0.6, width: 'narrow', turbulent: true },
  z: { airflowClass: 'fricative_strong', oral: 0.72, velocity: 0.56, width: 'narrow', turbulent: true },
  sh: { airflowClass: 'fricative_strong', oral: 0.74, velocity: 0.58, width: 'medium', turbulent: true },
  zh: { airflowClass: 'fricative_strong', oral: 0.7, velocity: 0.54, width: 'medium', turbulent: true },
  r: { airflowClass: 'uvular_fricative', oral: 0.72, velocity: 0.58, width: 'medium', turbulent: true },
  m: { airflowClass: 'nasal', oral: 0.04, nasal: 0.74, velocity: 0.4, width: 'medium', turbulent: false },
  n: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.38, width: 'medium', turbulent: false },
  ny: { airflowClass: 'nasal', oral: 0.03, nasal: 0.7, velocity: 0.36, width: 'medium', turbulent: false },
  an: { airflowClass: 'nasal_vowel', oral: 0.24, nasal: 0.48, velocity: 0.34, width: 'medium' },
  on: { airflowClass: 'nasal_vowel', oral: 0.22, nasal: 0.5, velocity: 0.34, width: 'medium' },
  in: { airflowClass: 'nasal_vowel', oral: 0.2, nasal: 0.52, velocity: 0.32, width: 'medium' },
  un: { airflowClass: 'nasal_vowel', oral: 0.2, nasal: 0.5, velocity: 0.32, width: 'medium' },
  l: { airflowClass: 'liquid', oral: 0.38, velocity: 0.3, width: 'medium', turbulent: false },
  y: { airflowClass: 'glide', oral: 0.28, velocity: 0.22, width: 'narrow', turbulent: false },
  wa: { airflowClass: 'glide', oral: 0.34, velocity: 0.28, width: 'narrow', turbulent: false },
  a: { airflowClass: 'vowel_short', oral: 0.6, velocity: 0.38, width: 'medium' },
  e: { airflowClass: 'vowel_short', oral: 0.56, velocity: 0.34, width: 'medium' },
  i: { airflowClass: 'vowel_short', oral: 0.54, velocity: 0.32, width: 'medium' },
  o: { airflowClass: 'vowel_short', oral: 0.58, velocity: 0.36, width: 'medium' },
  u: { airflowClass: 'vowel_short', oral: 0.56, velocity: 0.34, width: 'medium' },
  oo: { airflowClass: 'vowel_long', oral: 0.58, velocity: 0.36, width: 'medium' },
  eu: { airflowClass: 'vowel_long', oral: 0.56, velocity: 0.34, width: 'medium' },
};

export default airflowOverrides;