const airflowTransitions = {
  'closure->stop_unaspirated': { attack: 0.24, release: 0.2, sustain: 0.14 },
  'stop_unaspirated->vowel_short': { attack: 0.18, release: 0.18, sustain: 0.74 },
  'stop_unaspirated->vowel_long': { attack: 0.18, release: 0.2, sustain: 0.82 },
  'vowel_short->vowel_short': { blend: 0.56 },
  'vowel_short->vowel_long': { blend: 0.6 },
  'vowel_long->vowel_short': { blend: 0.6 },
  'vowel_long->vowel_long': { blend: 0.64 },
  'fricative_weak->vowel_short': { soften: 0.26 },
  'fricative_weak->vowel_long': { soften: 0.3 },
  'fricative_strong->vowel_short': { soften: 0.28 },
  'fricative_strong->vowel_long': { soften: 0.32 },
  'uvular_fricative->vowel_short': { soften: 0.3, turbulenceRampDown: 0.28 },
  'uvular_fricative->vowel_long': { soften: 0.34, turbulenceRampDown: 0.3 },
  'nasal_vowel->stop_unaspirated': { blend: 0.36, nasalFade: 0.34 },
  'nasal_vowel->fricative_strong': { blend: 0.38, nasalFade: 0.32 },
  'nasal_vowel->vowel_short': { blend: 0.48, nasalFade: 0.26 },
  'nasal_vowel->vowel_long': { blend: 0.52, nasalFade: 0.28 },
  'nasal->vowel_short': { blend: 0.4, nasalFade: 0.24 },
  'nasal->vowel_long': { blend: 0.44, nasalFade: 0.26 },
  'liquid->vowel_short': { blend: 0.46 },
  'liquid->vowel_long': { blend: 0.5 },
  'glide->vowel_short': { blend: 0.5 },
  'glide->vowel_long': { blend: 0.54 },
  'liaison_bridge->vowel_short': { bridge: 0.62 },
  'liaison_bridge->vowel_long': { bridge: 0.66 },
  'vowel_short->liaison_bridge': { bridge: 0.6 },
  'vowel_long->liaison_bridge': { bridge: 0.64 },
};

export default airflowTransitions;