const airflowOverrides = {
  q: { airflowClass: 'geminate_hold', oral: 0.01, velocity: 0.02, width: 'narrow', turbulent: false },
  n: { airflowClass: 'moraic_n', oral: 0.02, nasal: 0.58, velocity: 0.28, width: 'narrow', turbulent: false },

  shi: { airflowClass: 'fricative_soft', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  sha: { airflowClass: 'fricative_soft', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  shu: { airflowClass: 'fricative_soft', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  sho: { airflowClass: 'fricative_soft', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  fu: { airflowClass: 'fricative_soft', oral: 0.54, velocity: 0.42, width: 'medium', turbulent: true },
  hi: { airflowClass: 'fricative_soft', oral: 0.52, velocity: 0.4, width: 'medium', turbulent: true },
  hya: { airflowClass: 'fricative_soft', oral: 0.54, velocity: 0.42, width: 'medium', turbulent: true },
  hyu: { airflowClass: 'fricative_soft', oral: 0.54, velocity: 0.42, width: 'medium', turbulent: true },
  hyo: { airflowClass: 'fricative_soft', oral: 0.54, velocity: 0.42, width: 'medium', turbulent: true },

  sa: { airflowClass: 'fricative_strong', oral: 0.7, velocity: 0.56, width: 'medium', turbulent: true },
  su: { airflowClass: 'fricative_strong', oral: 0.7, velocity: 0.56, width: 'medium', turbulent: true },
  se: { airflowClass: 'fricative_strong', oral: 0.68, velocity: 0.54, width: 'medium', turbulent: true },
  so: { airflowClass: 'fricative_strong', oral: 0.68, velocity: 0.54, width: 'medium', turbulent: true },
  za: { airflowClass: 'fricative_soft', oral: 0.58, velocity: 0.46, width: 'medium', turbulent: true },
  zu: { airflowClass: 'fricative_soft', oral: 0.56, velocity: 0.44, width: 'medium', turbulent: true },
  ze: { airflowClass: 'fricative_soft', oral: 0.56, velocity: 0.44, width: 'medium', turbulent: true },
  zo: { airflowClass: 'fricative_soft', oral: 0.56, velocity: 0.44, width: 'medium', turbulent: true },

  chi: { airflowClass: 'affricate', oral: 0.64, velocity: 0.58, width: 'medium', turbulent: true },
  tsu: { airflowClass: 'affricate', oral: 0.66, velocity: 0.6, width: 'medium', turbulent: true },
  cha: { airflowClass: 'affricate', oral: 0.66, velocity: 0.6, width: 'medium', turbulent: true },
  chu: { airflowClass: 'affricate', oral: 0.66, velocity: 0.6, width: 'medium', turbulent: true },
  cho: { airflowClass: 'affricate', oral: 0.66, velocity: 0.6, width: 'medium', turbulent: true },
  ji: { airflowClass: 'affricate', oral: 0.6, velocity: 0.52, width: 'medium', turbulent: true },
  ja: { airflowClass: 'affricate', oral: 0.62, velocity: 0.54, width: 'medium', turbulent: true },
  ju: { airflowClass: 'affricate', oral: 0.62, velocity: 0.54, width: 'medium', turbulent: true },
  jo: { airflowClass: 'affricate', oral: 0.62, velocity: 0.54, width: 'medium', turbulent: true },

  ma: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.4, width: 'medium', turbulent: false },
  mi: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.4, width: 'medium', turbulent: false },
  mu: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.4, width: 'medium', turbulent: false },
  me: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.4, width: 'medium', turbulent: false },
  mo: { airflowClass: 'nasal', oral: 0.04, nasal: 0.72, velocity: 0.4, width: 'medium', turbulent: false },
  na: { airflowClass: 'nasal', oral: 0.04, nasal: 0.7, velocity: 0.38, width: 'medium', turbulent: false },
  ni: { airflowClass: 'nasal', oral: 0.04, nasal: 0.7, velocity: 0.38, width: 'medium', turbulent: false },
  nu: { airflowClass: 'nasal', oral: 0.04, nasal: 0.7, velocity: 0.38, width: 'medium', turbulent: false },
  ne: { airflowClass: 'nasal', oral: 0.04, nasal: 0.7, velocity: 0.38, width: 'medium', turbulent: false },
  no: { airflowClass: 'nasal', oral: 0.04, nasal: 0.7, velocity: 0.38, width: 'medium', turbulent: false },
  nya: { airflowClass: 'nasal', oral: 0.03, nasal: 0.68, velocity: 0.36, width: 'medium', turbulent: false },
  nyu: { airflowClass: 'nasal', oral: 0.03, nasal: 0.68, velocity: 0.36, width: 'medium', turbulent: false },
  nyo: { airflowClass: 'nasal', oral: 0.03, nasal: 0.68, velocity: 0.36, width: 'medium', turbulent: false },

  ra: { airflowClass: 'liquid', oral: 0.34, velocity: 0.26, width: 'narrow', turbulent: false },
  ri: { airflowClass: 'liquid', oral: 0.34, velocity: 0.26, width: 'narrow', turbulent: false },
  ru: { airflowClass: 'liquid', oral: 0.34, velocity: 0.26, width: 'narrow', turbulent: false },
  re: { airflowClass: 'liquid', oral: 0.34, velocity: 0.26, width: 'narrow', turbulent: false },
  ro: { airflowClass: 'liquid', oral: 0.34, velocity: 0.26, width: 'narrow', turbulent: false },
  rya: { airflowClass: 'liquid', oral: 0.32, velocity: 0.24, width: 'narrow', turbulent: false },
  ryu: { airflowClass: 'liquid', oral: 0.32, velocity: 0.24, width: 'narrow', turbulent: false },
  ryo: { airflowClass: 'liquid', oral: 0.32, velocity: 0.24, width: 'narrow', turbulent: false },

  ya: { airflowClass: 'glide', oral: 0.3, velocity: 0.24, width: 'narrow', turbulent: false },
  yu: { airflowClass: 'glide', oral: 0.3, velocity: 0.24, width: 'narrow', turbulent: false },
  yo: { airflowClass: 'glide', oral: 0.3, velocity: 0.24, width: 'narrow', turbulent: false },
  wa: { airflowClass: 'glide', oral: 0.32, velocity: 0.26, width: 'narrow', turbulent: false },
  wo: { airflowClass: 'glide', oral: 0.3, velocity: 0.24, width: 'narrow', turbulent: false },

  a: { airflowClass: 'vowel_long', oral: 0.58, velocity: 0.36, width: 'medium' },
  i: { airflowClass: 'vowel_long', oral: 0.56, velocity: 0.34, width: 'medium' },
  u: { airflowClass: 'vowel_long', oral: 0.56, velocity: 0.34, width: 'medium' },
  e: { airflowClass: 'vowel_long', oral: 0.56, velocity: 0.34, width: 'medium' },
  o: { airflowClass: 'vowel_long', oral: 0.58, velocity: 0.36, width: 'medium' },
};

export default airflowOverrides;