const airflowTransitions = {
  'closure->stop_clean': { attack: 0.24, release: 0.2, sustain: 0.14 },
  'stop_clean->vowel_short': { attack: 0.18, release: 0.18, sustain: 0.72 },
  'stop_clean->vowel_long': { attack: 0.18, release: 0.2, sustain: 0.82 },
  'vowel_short->vowel_short': { blend: 0.5 },
  'vowel_short->vowel_long': { blend: 0.58 },
  'vowel_long->vowel_short': { blend: 0.58 },
  'vowel_long->vowel_long': { blend: 0.64 },
  'fricative_soft->vowel_short': { soften: 0.24 },
  'fricative_soft->vowel_long': { soften: 0.28 },
  'fricative_strong->vowel_short': { soften: 0.26 },
  'fricative_strong->vowel_long': { soften: 0.3 },
  'affricate->fricative_soft': { release: 0.2, turbulenceRamp: 0.24 },
  'affricate->fricative_strong': { release: 0.22, turbulenceRamp: 0.28 },
  'nasal->vowel_short': { blend: 0.34, nasalFade: 0.24 },
  'nasal->vowel_long': { blend: 0.38, nasalFade: 0.26 },
  'moraic_n->stop_clean': { hold: 0.32, release: 0.18, nasalFade: 0.3 },
  'moraic_n->vowel_short': { hold: 0.28, blend: 0.3, nasalFade: 0.28 },
  'moraic_n->vowel_long': { hold: 0.3, blend: 0.34, nasalFade: 0.3 },
  'geminate_hold->stop_clean': { hold: 0.5, release: 0.16 },
  'geminate_hold->fricative_soft': { hold: 0.5, release: 0.18, turbulenceRamp: 0.2 },
  'geminate_hold->fricative_strong': { hold: 0.5, release: 0.18, turbulenceRamp: 0.24 },
  'geminate_hold->affricate': { hold: 0.5, release: 0.2, turbulenceRamp: 0.26 },
  'liquid->vowel_short': { blend: 0.42 },
  'liquid->vowel_long': { blend: 0.46 },
  'glide->vowel_short': { blend: 0.46 },
  'glide->vowel_long': { blend: 0.52 },
};

export default airflowTransitions;