const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.02,
    nasal: 0,
    velocity: 0.05,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  stop_clean: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.44,
    nasal: 0,
    velocity: 0.46,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },
  fricative_soft: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.52,
    nasal: 0,
    velocity: 0.42,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.68,
    nasal: 0,
    velocity: 0.54,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  affricate: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.62,
    nasal: 0,
    velocity: 0.56,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.04,
    nasal: 0.7,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  moraic_n: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.02,
    nasal: 0.58,
    velocity: 0.28,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: true,
  },
  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.34,
    nasal: 0,
    velocity: 0.26,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.3,
    nasal: 0,
    velocity: 0.24,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.56,
    nasal: 0,
    velocity: 0.34,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.58,
    nasal: 0,
    velocity: 0.36,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  geminate_hold: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.01,
    nasal: 0,
    velocity: 0.03,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;