const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.03,
    nasal: 0,
    velocity: 0.07,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  stop_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.42,
    nasal: 0,
    velocity: 0.48,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },
  stop_aspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.68,
    nasal: 0,
    velocity: 0.76,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  fricative_soft: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.56,
    nasal: 0,
    velocity: 0.46,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.8,
    nasal: 0,
    velocity: 0.64,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  affricate_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.64,
    nasal: 0,
    velocity: 0.58,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  affricate_aspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.78,
    nasal: 0,
    velocity: 0.72,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.05,
    nasal: 0.72,
    velocity: 0.4,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.38,
    nasal: 0,
    velocity: 0.3,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.32,
    nasal: 0,
    velocity: 0.26,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.6,
    nasal: 0,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.66,
    nasal: 0,
    velocity: 0.42,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  syllable_tail: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.5,
    nasal: 0,
    velocity: 0.32,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;