const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.03,
    nasal: 0,
    velocity: 0.07,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  stop_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.48,
    nasal: 0,
    velocity: 0.5,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },
  fricative_weak: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.58,
    nasal: 0,
    velocity: 0.48,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.8,
    nasal: 0,
    velocity: 0.64,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  affricate: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.74,
    nasal: 0,
    velocity: 0.68,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.05,
    nasal: 0.72,
    velocity: 0.4,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.42,
    nasal: 0,
    velocity: 0.34,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  palatal_liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.38,
    nasal: 0,
    velocity: 0.3,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.32,
    nasal: 0,
    velocity: 0.26,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.64,
    nasal: 0,
    velocity: 0.42,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.68,
    nasal: 0,
    velocity: 0.44,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  geminate_hold: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.04,
    nasal: 0,
    velocity: 0.08,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;