const airflowOverrides = {
  p: { airflowClass: 'stop_unaspirated', oral: 0.46, velocity: 0.48, width: 'narrow', turbulent: false },
  b: { airflowClass: 'stop_unaspirated', oral: 0.4, velocity: 0.42, width: 'narrow', turbulent: false },
  t: { airflowClass: 'stop_unaspirated', oral: 0.48, velocity: 0.5, width: 'narrow', turbulent: false },
  d: { airflowClass: 'stop_unaspirated', oral: 0.42, velocity: 0.44, width: 'narrow', turbulent: false },
  k: { airflowClass: 'stop_unaspirated', oral: 0.52, velocity: 0.54, width: 'medium', turbulent: false },
  g: { airflowClass: 'stop_unaspirated', oral: 0.48, velocity: 0.5, width: 'medium', turbulent: false },
  s: { airflowClass: 'fricative_strong', oral: 0.84, velocity: 0.68, width: 'narrow', turbulent: true },
  sh: { airflowClass: 'fricative_strong', oral: 0.8, velocity: 0.64, width: 'medium', turbulent: true },
  f: { airflowClass: 'fricative_weak', oral: 0.62, velocity: 0.5, width: 'medium', turbulent: true },
  v: { airflowClass: 'fricative_weak', oral: 0.6, velocity: 0.48, width: 'medium', turbulent: true },
  ch: { airflowClass: 'affricate', oral: 0.76, velocity: 0.7, width: 'medium', turbulent: true },
  j: { airflowClass: 'affricate', oral: 0.74, velocity: 0.68, width: 'medium', turbulent: true },
  ts: { airflowClass: 'affricate', oral: 0.78, velocity: 0.72, width: 'medium', turbulent: true },
  m: { airflowClass: 'nasal', oral: 0.04, nasal: 0.76, velocity: 0.42, width: 'medium', turbulent: false },
  n: { airflowClass: 'nasal', oral: 0.04, nasal: 0.74, velocity: 0.4, width: 'medium', turbulent: false },
  ny: { airflowClass: 'nasal', oral: 0.03, nasal: 0.72, velocity: 0.38, width: 'medium', turbulent: false },
  l: { airflowClass: 'liquid', oral: 0.42, velocity: 0.34, width: 'medium', turbulent: false },
  r: { airflowClass: 'liquid', oral: 0.46, velocity: 0.38, width: 'medium', turbulent: false },
  ly: { airflowClass: 'palatal_liquid', oral: 0.38, velocity: 0.3, width: 'medium', turbulent: false },
  y: { airflowClass: 'glide', oral: 0.3, velocity: 0.24, width: 'narrow', turbulent: false },
  w: { airflowClass: 'glide', oral: 0.34, velocity: 0.28, width: 'narrow', turbulent: false },
  a: { airflowClass: 'vowel_short', oral: 0.68, velocity: 0.44, width: 'medium' },
  e: { airflowClass: 'vowel_short', oral: 0.62, velocity: 0.4, width: 'medium' },
  i: { airflowClass: 'vowel_short', oral: 0.58, velocity: 0.38, width: 'medium' },
  o: { airflowClass: 'vowel_short', oral: 0.66, velocity: 0.42, width: 'medium' },
  u: { airflowClass: 'vowel_short', oral: 0.62, velocity: 0.4, width: 'medium' },
  rr: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  ll: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  tt: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  cc: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  gg: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  pp: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  dd: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  bb: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  kk: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  ss: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
  zz: { airflowClass: 'geminate_hold', oral: 0.05, velocity: 0.09, width: 'narrow', turbulent: false },
};

export default airflowOverrides;