const airflowProfiles = {
  silence: {
    pattern: 'breathing',
    origin: 'nose',
    exit: 'lungs',
    oral: 0,
    nasal: 0,
    velocity: 0,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  closure: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.03,
    nasal: 0,
    velocity: 0.07,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  stop_unaspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.42,
    nasal: 0,
    velocity: 0.44,
    width: 'narrow',
    burst: true,
    turbulent: false,
    split: false,
  },
  stop_aspirated: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.48,
    nasal: 0,
    velocity: 0.52,
    width: 'medium',
    burst: true,
    turbulent: false,
    split: false,
  },
  fricative_weak: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.54,
    nasal: 0,
    velocity: 0.44,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  fricative_strong: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.72,
    nasal: 0,
    velocity: 0.58,
    width: 'medium',
    burst: false,
    turbulent: true,
    split: false,
  },
  affricate: {
    pattern: 'burst',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.7,
    nasal: 0,
    velocity: 0.64,
    width: 'medium',
    burst: true,
    turbulent: true,
    split: false,
  },
  nasal: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'nose',
    oral: 0.05,
    nasal: 0.7,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  nasal_vowel: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.26,
    nasal: 0.44,
    velocity: 0.36,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: true,
  },
  liquid: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.36,
    nasal: 0,
    velocity: 0.3,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  glide: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.3,
    nasal: 0,
    velocity: 0.24,
    width: 'narrow',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_short: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.6,
    nasal: 0,
    velocity: 0.38,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
  vowel_long: {
    pattern: 'continuous',
    origin: 'lungs',
    exit: 'mouth',
    oral: 0.64,
    nasal: 0,
    velocity: 0.4,
    width: 'medium',
    burst: false,
    turbulent: false,
    split: false,
  },
};

export default airflowProfiles;